# -*- coding: utf-8 -*-
"""deliverable-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/DQSpan/3956e56e62c839800bdf35a9a6cab288/deliverable-6.ipynb
"""

# Step(1): Importing Libraries
import pandas as pd
import numpy as np
import seaborn as sns

# Step(2): Loading iris dataset
iris = sns.load_dataset('iris')
iris.head()

# Step(3): Dropping the "species" column
iris.drop(labels = 'species', axis = 1, inplace = True)
iris.head()

# Step(4): Adding columns
iris['sepal_sum'] = iris['sepal_length'] + iris['sepal_width']
iris['petal_sum'] = iris['petal_length'] + iris['petal_width']
iris.head()

# Step(5): Create table with mean, standard deviation, minimum, and maximum
mean = [np.mean(iris['sepal_length']), 
        np.mean(iris['sepal_width']),
        np.mean(iris['sepal_sum']),
        np.mean(iris['petal_length']),
        np.mean(iris['petal_width']),
        np.mean(iris['petal_sum'])]

std = [np.std(iris['sepal_length']), 
        np.std(iris['sepal_width']),
        np.std(iris['sepal_sum']),
        np.std(iris['petal_length']),
        np.std(iris['petal_width']),
        np.std(iris['petal_sum'])]

min = [np.min(iris['sepal_length']), 
        np.min(iris['sepal_width']),
        np.min(iris['sepal_sum']),
        np.min(iris['petal_length']),
        np.min(iris['petal_width']),
        np.min(iris['petal_sum'])]

max = [np.max(iris['sepal_length']), 
        np.max(iris['sepal_width']),
        np.max(iris['sepal_sum']),
        np.max(iris['petal_length']),
        np.max(iris['petal_width']),
        np.max(iris['petal_sum'])]


summary_dict = {'mean':mean, 'std':std, 'min':min, 'max':max}
summary_df = pd.DataFrame(data = summary_dict, index = list(iris.columns))
summary_df